default: &default
  adapter: postgresql
  encoding: unicode
  host:     <%= ENV.fetch('PGHOST', 'localhost') %>
  username: <%= ENV.fetch('PGUSER', 'admin') %>
  password: <%= ENV.fetch('PGPASSWORD', 'password') %>
  port:     <%= ENV.fetch('PGPORT', '5432') %>
  pool:     <%= ENV.fetch('DB_POOL', 5) %>
  timeout: 5000
  reaping_frequency: <%= ENV.fetch('DB_REAPING_FREQUENCY', 10) %>

development:
  <<: *default
  database: daisy_development

production: &production
  <<: *default
  database: <%= ENV.fetch('PGDATABASE', 'daisy') %>

staging:
  <<: *production
  database: <%= ENV.fetch('PGDATABASE', 'daisy_staging') %>

test:
  adapter: postgresql
  host:     <%= ENV.fetch('PGHOST', 'localhost') %>
  username: <%= ENV.fetch('PGUSER', nil) %>
  password: <%= ENV.fetch('PGPASSWORD', 'password') %>
  database: daisy_test
