default: &default
  adapter: postgresql
  encoding: unicode
  timeout: 5000


development:
  <<: *default
  database: daisy_development

production: &production
  <<: *default
  database: <%= ENV.fetch('PGDATABASE', 'daisy') %>

staging:
  <<: *production
  database: <%= ENV.fetch('PGDATABASE', 'daisy_staging') %>

test:
  adapter: postgresql
  host:     <%= ENV.fetch('PGHOST', 'localhost') %>
  username: <%= ENV.fetch('PGUSER', nil) %>
  password: <%= ENV.fetch('PGPASSWORD', 'password') %>
  database: daisy_test
