# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dfbfc061cf0f9630ac67db323ca6e3def758ce5fca728394ffe78f7198b4433750e0867a07edb200f9205e24775882f5178645bdd46458726a209a74f7e6ac75

test:
  secret_key_base: c60e3fc1079e9a84a017c449d00c81a7b3159deb22d7bed61ec741c144e85dce92a969d6ed7f1c4d09df61d03f2bf7534a1d6f1ee476a2ce4fc0066895fc95a4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
