# Place all the behaviors and hooks related to the matching controller here.
# All this logic will automatically be available in application.js.
# You can use CoffeeScript in this file: http://coffeescript.org/

$(document).on 'ready page:load', ->
  if $('#eventPage').length != 0
    img = document.getElementById('eventPage')
    if img.currentStyle != 0
      style = img.currentStyle or window.getComputedStyle(img, false)
      bi = style.backgroundImage.slice(4, -1)
      bi = style.backgroundImage.slice(4, -1).replace(/"/g, '')
      
      sourceImage =  bi

      oImg = document.createElement('img')
      oImg.setAttribute 'src', bi
      oImg.setAttribute 'width', '100px'
      oImg.setAttribute 'height', '100px'


       
      oImg.onload = ->
        `var colorThief`
        colorThief = new ColorThief
        photoColor = colorThief.getColor(oImg)
        console.log photoColor 
        $('#attendee-form').css 'backgroundColor', 'rgb(' + photoColor[0] + ',' + photoColor[1] + ',' + photoColor[2] + ')'
        return



  formArray = $('.event-registration .field')
  percentRange = 100 / formArray.length
  currentIndex = 0
  $('.event-registration .field').addClass 'slide-down-hide'
  $(formArray[0]).removeClass('slide-down-hide').addClass 'slide-up-show'
  $('.event-preview').hide()
  $('.side-nav li a').on 'click', (e) ->
   
    e.preventDefault()
    $('.side-nav li a').removeClass 'active'
    $(this).addClass 'active'
    if currentIndex < $(this).parent().index()
      $('.event-registration .field').removeClass('slide-up-hide slide-up-show slide-down-show').addClass 'slide-up-hide'
    else
      $('.event-registration .field').removeClass('slide-up-hide slide-up-show slide-down-show').addClass 'slide-down-hide'
    currentIndex = $(this).parent().index() - 1
    console.log (currentIndex + 1) * percentRange
    $(formArray[currentIndex]).removeClass('slide-up-hide slide-down-hide').addClass 'slide-up-hide'
    $(formArray[currentIndex + 1]).removeClass('slide-down-hide slide-up-hide').addClass 'slide-up-show'
    $('.percent span').animate { 'width': (currentIndex + 1) * percentRange + '%' }, 500
    console.log 'currentIndex ' + currentIndex + 2 + '|| length of nav' + $('.side-nav li a').length
    # if((currentIndex+2) == $('.side-nav li a').length) {
    #     $('.field').hide();
    #     $('.event-preview').show();
    #     $('.event-bg').css({'background-style': 'url(http://placehold.it/300x300)'});
    #     $('.event-preview h1').text('title of event');
    #     $('.event-preview p.lead').text('TIME OF SOMETHING'+' | '+ 'LOCATION OF SOMETHING');
    # } else {
    # $('.event-registration .field').show();
    # $('.event-preview').hide();
    # }
    return
  $('.btn-prev').on 'click', (e) ->
    e.preventDefault()
    $('.side-nav li a.active').parent().prev().find('a').click()
    return
  $('.btn-next').on 'click', (e) ->
    e.preventDefault()
    console.log $('.side-nav li a.active').parent().next().find('a').index()
    $('.side-nav li a.active').parent().next().find('a').click()
    return
  return

# ---
# generated by js2coffee 2.1.0